# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-gobo2024
    - name: Install dependencies
      run: |
        poetry install --only=main

  dynamic-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-gobo2024
    - name: Install dependencies
      run: |
        poetry install --only=dynamic-test
    - name: Test with pytest
      run: |
        poetry run pytest

  static-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-gobo2024
    - name: Install dependencies
      run: |
        poetry install --only=static-test
    - name: Lint with ruff
      run: |
        poetry run ruff check
