# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install poetry
      run: pipx install poetry
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: "poetry"
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install poetry poetry-plugin-export
        poetry export --without-hashes --only=main,static-test,dynamic-test | pip install -r /dev/stdin
    - name: Lint with ruff
      run: |
        ruff check
    - name: Test with pytest
      run: |
        pytest
